# Generated by Django 3.0.1 on 2020-05-07 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('onboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Closet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField(verbose_name='Floor')),
                ('category', models.CharField(choices=[('IDF', 'IDF'), ('MDF', 'MDF'), ('MDF & IDF', 'MDF & IDF')], default='IDF', max_length=9, verbose_name='Closet Type')),
                ('closet', models.CharField(blank=True, max_length=4, verbose_name='Closet')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboard.Site')),
            ],
        ),
    ]
