# Generated by Django 3.0.1 on 2020-01-08 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='interface',
            field=models.CharField(choices=[('GigabitEthernet0/0/0', 'GigE0/0/0'), ('GigabitEthernet0/0/1', 'GigE0/0/1')], default='GigabitEthernet0/0/0', max_length=100),
        ),
        migrations.AlterField(
            model_name='router',
            name='hostname',
            field=models.CharField(max_length=19),
        ),
    ]
