# Generated by Django 3.0.1 on 2020-05-04 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoreGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=19, verbose_name='Router Hostname')),
                ('loopback_ip', models.GenericIPAddressField(protocol='IPv4', verbose_name='Loopback IP')),
                ('loopback_desc', models.CharField(max_length=26)),
                ('uplink_1_intr', models.CharField(max_length=20)),
                ('uplink_1_desc', models.CharField(max_length=37)),
                ('uplink_1_ip', models.GenericIPAddressField(protocol='IPv4', verbose_name='Uplink 1 IP')),
                ('uplink_2_intr', models.CharField(max_length=20)),
                ('uplink_2_desc', models.CharField(max_length=37)),
                ('uplink_2_ip', models.GenericIPAddressField(protocol='IPv4', verbose_name='Uplink 2 IP')),
                ('intralink_1_intr', models.CharField(max_length=20)),
                ('intralink_2_intr', models.CharField(max_length=20)),
                ('interlink_1_intr', models.CharField(max_length=20)),
                ('interlink_2_intr', models.CharField(max_length=20)),
                ('wlc_intr_1', models.CharField(max_length=20)),
                ('wlc_intr_2', models.CharField(max_length=20)),
                ('wlc_ha_intr', models.CharField(max_length=20)),
                ('dual_intr_1', models.CharField(max_length=20)),
                ('dual_intr_2', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CoreVlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlan_type', models.CharField(choices=[('data', 'Data'), ('security', 'Security'), ('voice', 'Voice'), ('voice_infra', 'Voice Infrastructure'), ('server', 'Server')], max_length=20, verbose_name='VLAN Type')),
                ('vlan_id', models.IntegerField(verbose_name='VLAN ID')),
                ('vlan_ip', models.GenericIPAddressField(protocol='IPv4', verbose_name='SVI IP')),
                ('vlan_subnet', models.GenericIPAddressField(protocol='IPv4', verbose_name='SVI Subnet')),
            ],
        ),
    ]
