# Generated by Django 3.0.1 on 2020-03-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=512, null=True, verbose_name='Site Address')),
                ('capacity', models.IntegerField(blank=True, null=True, verbose_name='Site Capacity')),
                ('crest', models.IntegerField(verbose_name='Site CREST ID')),
                ('headcount', models.IntegerField(blank=True, null=True, verbose_name='Site Headcount')),
                ('nearest_dc', models.CharField(blank=True, choices=[('am1', 'AM1'), ('am2', 'AM2')], max_length=4, null=True, verbose_name='Nearest DC to Site')),
                ('project_type', models.CharField(choices=[('brownfield', 'Brownfield'), ('greenfield', 'Greenfield')], default='greenfield', max_length=10, verbose_name='Type of Project')),
            ],
        ),
    ]
