# Generated by Django 3.0.1 on 2020-04-16 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crest', models.IntegerField(verbose_name='Site CREST ID')),
                ('project_type', models.CharField(choices=[('brownfield', 'Brownfield'), ('greenfield', 'Greenfield')], default='greenfield', max_length=10, verbose_name='Type of Project')),
                ('address', models.CharField(max_length=128, null=True, verbose_name='Site Address')),
                ('capacity', models.IntegerField(null=True, verbose_name='Site Capacity')),
                ('headcount', models.IntegerField(null=True, verbose_name='Site Headcount')),
                ('nearest_dc', models.CharField(choices=[('am1', 'AM1'), ('am2', 'AM2')], max_length=4, null=True, verbose_name='Nearest DC to Site')),
                ('router', models.CharField(choices=[('asr_1001_x', 'ASR 1001-X'), ('asr_1001_hx', 'ASR 1001-HX'), ('isr_4331', 'ISR 4331'), ('isr_4351', 'ISR 4351'), ('isr_4451', 'ISR 4451')], max_length=11, null=True, verbose_name='Router Layer')),
                ('core', models.CharField(choices=[('no_core', 'No Core Layer'), ('catalyst_3850', 'Catalyst 3850'), ('catalyst_6840', 'Catalyst 6840'), ('catalyst_6880', 'Catalyst 6880'), ('catalyst_9500', 'Catalyst 9500')], max_length=13, null=True, verbose_name='Core Layer')),
                ('server', models.CharField(choices=[('no_server', 'No Server Layer'), ('catalyst_4500', 'Catalyst 4500'), ('catalyst_9500', 'Catalyst 9500')], max_length=15, null=True, verbose_name='Server Layer')),
                ('exception_confirmed', models.BooleanField(null=True, verbose_name='Exception Present & Confirmed')),
            ],
        ),
        migrations.CreateModel(
            name='StaticSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.GenericIPAddressField(protocol='IPv4', verbose_name='Summary Subnet Network')),
                ('mask', models.GenericIPAddressField(protocol='IPv4', verbose_name='Summary Subnet Mask')),
                ('overview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overview.Overview')),
            ],
        ),
    ]
