# Generated by Django 3.0.1 on 2020-05-06 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('onboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supernet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supernet_cidr', models.CharField(max_length=18, verbose_name='Supernet CIDR')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboard.Site')),
            ],
        ),
        migrations.CreateModel(
            name='ExcludedSubnet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subnet_cidr', models.CharField(max_length=18, verbose_name='Excluded Subnet CIDR')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboard.Site')),
            ],
        ),
    ]
