# Generated by Django 3.0.1 on 2020-03-23 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='overview',
            name='address',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='overview',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overview',
            name='headcount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overview',
            name='nearest_dc',
            field=models.CharField(blank=True, choices=[('am1', 'Am1'), ('am2', 'Am2')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='overview',
            name='project_type',
            field=models.CharField(choices=[('brownfield', 'Brownfield'), ('greenfield', 'Greenfield')], default='greenfield', max_length=10),
        ),
    ]
