# Generated by Django 3.0.1 on 2020-03-23 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0002_auto_20200323_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overview',
            name='nearest_dc',
            field=models.CharField(blank=True, choices=[('am1', 'AM1'), ('am2', 'AM2')], max_length=4, null=True),
        ),
    ]
