# Generated by Django 3.0.1 on 2020-03-23 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0003_auto_20200323_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overview',
            name='project_type',
            field=models.CharField(choices=[('brownfield', 'Brownfield'), ('greenfield', 'Greenfield')], default='greenfield', max_length=10, verbose_name='Project Type'),
        ),
    ]
