# Generated by Django 3.0.1 on 2020-03-23 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0004_auto_20200323_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overview',
            name='address',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Site Address'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Site Capacity'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='crest',
            field=models.IntegerField(verbose_name='Site CREST ID'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='headcount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Site Headcount'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='nearest_dc',
            field=models.CharField(blank=True, choices=[('am1', 'AM1'), ('am2', 'AM2')], max_length=4, null=True, verbose_name='Nearest DC to Site'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='project_type',
            field=models.CharField(choices=[('brownfield', 'Brownfield'), ('greenfield', 'Greenfield')], default='greenfield', max_length=10, verbose_name='Type of Project'),
        ),
    ]
