# Generated by Django 3.0.1 on 2020-04-22 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('overview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Closets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField(verbose_name='Floor Number')),
                ('category', models.CharField(choices=[('idf', 'IDF'), ('mdf', 'MDF'), ('mdf_idf', 'MDF & IDF')], default='idf', max_length=9, verbose_name='Type of Closet')),
                ('overview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overview.Overview')),
            ],
        ),
    ]
