# Generated by Django 3.0.1 on 2020-03-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closets',
            name='category',
            field=models.CharField(choices=[('idf', 'IDF'), ('mdf', 'MDF'), ('mdf_idf', 'MDF & IDF')], default='idf', max_length=9, verbose_name='Type of Closet'),
        ),
    ]
