# Generated by Django 3.0.1 on 2020-04-16 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('closets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=19, verbose_name='Router Hostname')),
                ('loopback_ip', models.GenericIPAddressField(protocol='IPv4', verbose_name='Loopback IP')),
                ('downlink_1_intr', models.CharField(max_length=20)),
                ('downlink_1_desc', models.CharField(max_length=37)),
                ('downlink_1_ip', models.GenericIPAddressField(protocol='IPv4', verbose_name='Downlink 1 IP')),
                ('downlink_2_intr', models.CharField(max_length=20)),
                ('downlink_2_desc', models.CharField(max_length=37)),
                ('downlink_2_ip', models.GenericIPAddressField(protocol='IPv4', verbose_name='Downlink 1 IP')),
                ('interlink_1_intr', models.CharField(max_length=20)),
                ('interlink_1_desc', models.CharField(max_length=37)),
                ('interlink_1_ip', models.GenericIPAddressField(protocol='IPv4', verbose_name='Interlink 1 IP')),
                ('interlink_2_intr', models.CharField(max_length=20)),
                ('interlink_2_desc', models.CharField(max_length=37)),
                ('interlink_2_ip', models.GenericIPAddressField(protocol='IPv4', verbose_name='Interlink 1 IP')),
                ('wan_intr', models.CharField(max_length=20)),
                ('wan_desc', models.CharField(max_length=200)),
                ('wan_ip', models.GenericIPAddressField(protocol='IPv4', verbose_name='WAN IP')),
                ('wan_bw', models.IntegerField(verbose_name='Circuit Bandwidth')),
                ('local_asn', models.IntegerField(verbose_name='Local BGP ASN')),
                ('remote_asn', models.IntegerField(verbose_name='Remote BGP ASN')),
                ('closet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='closets.Closets')),
            ],
        ),
    ]
