# Generated by Django 3.0.1 on 2020-04-28 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('closet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=19, verbose_name='Hostname')),
                ('loopback_ip', models.CharField(blank=True, max_length=15, null=True, verbose_name='Loopback IP')),
                ('downlink_1_desc', models.CharField(max_length=37, null=True, verbose_name='Downlink#1 Description')),
                ('downlink_1_ip', models.CharField(blank=True, max_length=15, null=True, verbose_name='Downlink#1 IP')),
                ('downlink_2_desc', models.CharField(max_length=37, null=True, verbose_name='Downlink#2 Description')),
                ('downlink_2_ip', models.CharField(blank=True, max_length=15, null=True, verbose_name='Downlink#2 IP')),
                ('interlink_1_desc', models.CharField(max_length=37, null=True, verbose_name='Interlink#1 Description')),
                ('interlink_1_ip', models.CharField(blank=True, max_length=15, null=True, verbose_name='Interlink#1 IP')),
                ('interlink_2_desc', models.CharField(max_length=37, null=True, verbose_name='Interlink#2 Description')),
                ('interlink_2_ip', models.CharField(blank=True, max_length=15, null=True, verbose_name='Interlink#2 IP')),
                ('wan_type', models.CharField(choices=[('mpls', 'MPLS'), ('p2p', 'Point-to-Point')], default='mpls', max_length=10, null=True, verbose_name='WAN Type')),
                ('wan_provider', models.CharField(choices=[('att', 'AT&T'), ('bellcanada', 'Bell Canada'), ('centurylink', 'Century Link'), ('chinatelcom', 'China Telecom'), ('deutschetelekom', 'Deutsche Telekom'), ('embratel', 'Embratel'), ('free', 'Free'), ('gestiontelcom', 'Gestion Telcom'), ('globe', 'Globe'), ('kddi', 'KDDI'), ('koreatelcom', 'Korea Telcom'), ('level3', 'Level3'), ('mci', 'MCI'), ('mxis', 'MXIS'), ('nttcom', 'NTTCOM'), ('orange', 'Orange'), ('pccw', 'PCCW'), ('pldt', 'PLDT'), ('singtel', 'Singtel'), ('softbank', 'Softbank'), ('tata', 'Tata'), ('telcomargentina', 'Telcom Argentina'), ('telcommalaysia', 'Telcom Malaysia'), ('telefonica', 'Telefonica'), ('telstra', 'Telstra'), ('telus', 'Telus'), ('verizon', 'Verizon'), ('vodaphone', 'Vodafone'), ('zayo', 'Zayo')], max_length=20, null=True, verbose_name='WAN Provider')),
                ('access_id', models.CharField(max_length=80, null=True, verbose_name='Circuit Access ID')),
                ('port_id', models.CharField(max_length=80, null=True, verbose_name='Circuit Port ID')),
                ('access_bw', models.IntegerField(null=True, verbose_name='Circuit Access Bandwidth')),
                ('port_bw', models.IntegerField(null=True, verbose_name='Circuit Port Bandwidth')),
                ('wan_link_cidr', models.CharField(max_length=18, null=True, verbose_name='WAN Link CIDR')),
                ('local_asn', models.IntegerField(null=True, verbose_name='Local BGP ASN')),
                ('remote_asn', models.IntegerField(null=True, verbose_name='Remote BGP ASN')),
                ('other_router_loopback_ip', models.CharField(blank=True, max_length=15, null=True, verbose_name='Other Router Loopback IP')),
                ('other_router_hostname', models.CharField(max_length=19, null=True, verbose_name='Other Router Hostname')),
                ('isp_ip', models.CharField(blank=True, max_length=15, null=True, verbose_name='ISP IP')),
                ('closet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='closet.Closet')),
            ],
        ),
    ]
