# Generated by Django 3.0.1 on 2020-05-12 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('closet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=19, verbose_name='Hostname')),
                ('loopback_ip', models.CharField(blank=True, max_length=15, null=True, verbose_name='Loopback IP')),
                ('downlink_1_desc', models.CharField(max_length=37, null=True, verbose_name='Downlink#1 Description')),
                ('downlink_1_ip', models.CharField(blank=True, max_length=15, null=True, verbose_name='Downlink#1 IP')),
                ('downlink_2_desc', models.CharField(max_length=37, null=True, verbose_name='Downlink#2 Description')),
                ('downlink_2_ip', models.CharField(blank=True, max_length=15, null=True, verbose_name='Downlink#2 IP')),
                ('interlink_1_desc', models.CharField(max_length=37, null=True, verbose_name='Interlink#1 Description')),
                ('interlink_1_ip', models.CharField(blank=True, max_length=15, null=True, verbose_name='Interlink#1 IP')),
                ('interlink_2_desc', models.CharField(max_length=37, null=True, verbose_name='Interlink#2 Description')),
                ('interlink_2_ip', models.CharField(blank=True, max_length=15, null=True, verbose_name='Interlink#2 IP')),
                ('wan_type', models.CharField(choices=[('MPLS', 'MPLS'), ('Point-to-Point', 'Point-to-Point')], default='MPLS', max_length=14, verbose_name='WAN Type')),
                ('wan_provider', models.CharField(choices=[('AT&T', 'AT&T'), ('Bell Canada', 'Bell Canada'), ('Century Link', 'Century Link'), ('China Telecom', 'China Telecom'), ('Deutsche Telekom', 'Deutsche Telekom'), ('Embratel', 'Embratel'), ('Free', 'Free'), ('Gestion Telcom', 'Gestion Telcom'), ('Globe', 'Globe'), ('KDDI', 'KDDI'), ('Korea Telcom', 'Korea Telcom'), ('Level3', 'Level3'), ('MCI', 'MCI'), ('MXIS', 'MXIS'), ('NTTCOM', 'NTTCOM'), ('Orange', 'Orange'), ('PCCW', 'PCCW'), ('PLDT', 'PLDT'), ('Singtel', 'Singtel'), ('Softbank', 'Softbank'), ('Tata', 'Tata'), ('Telcom Argentina', 'Telcom Argentina'), ('Telcom Malaysia', 'Telcom Malaysia'), ('Telefonica', 'Telefonica'), ('Telstra', 'Telstra'), ('Telus', 'Telus'), ('Verizon', 'Verizon'), ('Vodafone', 'Vodafone'), ('Zayo', 'Zayo')], max_length=20, verbose_name='WAN Provider')),
                ('access_id', models.CharField(max_length=80, verbose_name='Circuit Access ID')),
                ('port_id', models.CharField(max_length=80, verbose_name='Circuit Port ID')),
                ('access_bw', models.IntegerField(verbose_name='Circuit Access Bandwidth')),
                ('port_bw', models.IntegerField(verbose_name='Circuit Port Bandwidth')),
                ('wan_link_cidr', models.CharField(max_length=18, verbose_name='WAN Link CIDR')),
                ('local_asn', models.IntegerField(verbose_name='Local BGP ASN')),
                ('remote_asn', models.IntegerField(verbose_name='Remote BGP ASN')),
                ('other_router_loopback_ip', models.CharField(blank=True, max_length=15, null=True, verbose_name='Other Router Loopback IP')),
                ('other_router_hostname', models.CharField(max_length=19, null=True, verbose_name='Other Router Hostname')),
                ('isp_ip', models.CharField(blank=True, max_length=15, null=True, verbose_name='ISP IP')),
                ('closet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='closet.Closet')),
            ],
        ),
    ]
