# Generated by Django 3.0.1 on 2020-04-29 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('closet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessSwitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=19, verbose_name='Hostname')),
                ('stack_model', models.CharField(blank=True, choices=[('catalyst_3850', 'Catalyst 3850'), ('catalyst_9300', 'Catalyst 9300')], default='catalyst_9300', max_length=13, null=True, verbose_name='Access Stack Model')),
                ('switch_count', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')], null=True, verbose_name='Total Switch#')),
                ('mgig_count', models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')], default=0, null=True, verbose_name='MGig Switch#')),
                ('loopback_ip', models.CharField(blank=True, max_length=15, null=True, verbose_name='Loopback IP')),
                ('uplink_1_desc', models.CharField(max_length=37, null=True, verbose_name='Uplink#1 Description')),
                ('uplink_1_ip', models.CharField(blank=True, max_length=15, null=True, verbose_name='Uplink#1 IP')),
                ('uplink_2_desc', models.CharField(max_length=37, null=True, verbose_name='Uplink#2 Description')),
                ('uplink_2_ip', models.CharField(blank=True, max_length=15, null=True, verbose_name='Uplink#2 IP')),
                ('ap_count', models.IntegerField(blank=True, null=True, verbose_name='AP Count')),
                ('closet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='closet.Closet')),
            ],
        ),
        migrations.CreateModel(
            name='Vlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlan_type', models.CharField(blank=True, choices=[('data', 'Data'), ('voice', 'Voice'), ('security', 'Security'), ('server', 'Server'), ('voice_server', 'Voice Server')], max_length=12, null=True, verbose_name='VLAN Type')),
                ('vlan_id', models.IntegerField(blank=True, null=True, verbose_name='VLAN ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='VLAN Name')),
                ('svi_ip', models.CharField(blank=True, max_length=15, null=True, verbose_name='SVI IP')),
                ('svi_mask_length', models.CharField(blank=True, choices=[('ml_23', '/23'), ('ml_24', '/24'), ('ml_25', '/25'), ('ml_26', '/26'), ('ml_27', '/27'), ('ml_28', '/28'), ('ml_29', '/29')], max_length=5, null=True, verbose_name='SVI Mask')),
                ('access_switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access.AccessSwitch')),
            ],
        ),
        migrations.CreateModel(
            name='AccessPortBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_intr', models.CharField(max_length=21, verbose_name='Start Interface')),
                ('end_intr', models.CharField(max_length=21, verbose_name='End Interface')),
                ('access_vlan', models.IntegerField(verbose_name='Access VLAN')),
                ('voice_vlan', models.IntegerField(verbose_name='Voice VLAN')),
                ('legacy_qos', models.BooleanField(default=False, verbose_name='Apply Legacy QoS')),
                ('access_switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access.AccessSwitch')),
            ],
        ),
    ]
