# Generated by Django 3.0.1 on 2020-04-29 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crest', models.IntegerField(verbose_name='CREST ID')),
                ('project_type', models.CharField(choices=[('brownfield', 'Brownfield'), ('greenfield', 'Greenfield')], default='greenfield', max_length=10, verbose_name='Projet Type')),
                ('network_name', models.CharField(max_length=96, verbose_name='Network Name')),
                ('address', models.CharField(max_length=96, verbose_name='Site Address')),
                ('capacity', models.IntegerField(verbose_name='Site Capacity')),
                ('headcount', models.IntegerField(verbose_name='Site Headcount')),
                ('network_type', models.CharField(choices=[('micro_branch', 'Micro Branch'), ('mini_branch', 'Mini Branch'), ('small_branch', 'Small Branch'), ('medium_branch_1', 'Medium Branch (1-2 Floors)'), ('medium_branch_2', 'Medium Branch (3-10 Floors)'), ('large_branch', 'Large Branch'), ('medium_campus', 'Medium Campus'), ('large_campus', 'Large Campus')], default='micro_branch', max_length=27, verbose_name='Network Type')),
                ('nearest_dc', models.CharField(choices=[('am1', 'AM1'), ('am2', 'AM2')], max_length=4, verbose_name='Nearest DC')),
                ('router', models.CharField(choices=[('asr_1001_x', 'ASR 1001-X'), ('asr_1001_hx', 'ASR 1001-HX'), ('isr_4331', 'ISR 4331'), ('isr_4351', 'ISR 4351'), ('isr_4451', 'ISR 4451')], max_length=11, verbose_name='Router Layer')),
                ('core', models.CharField(choices=[('no_core', 'No Core Layer'), ('catalyst_3850', 'Catalyst 3850'), ('catalyst_6840', 'Catalyst 6840'), ('catalyst_6880', 'Catalyst 6880'), ('catalyst_9500', 'Catalyst 9500')], max_length=13, verbose_name='Core Layer')),
                ('server', models.CharField(choices=[('no_server', 'No Server Layer'), ('catalyst_4500', 'Catalyst 4500'), ('catalyst_9500', 'Catalyst 9500')], max_length=15, verbose_name='Server Layer')),
                ('signal_created_access', models.BooleanField(null=True, verbose_name='Access Created')),
                ('signal_exception_site', models.BooleanField(null=True, verbose_name='Site Non-standard')),
                ('signal_onboarded_site', models.BooleanField(null=True, verbose_name='Site Onboarded')),
                ('signal_present_core', models.BooleanField(null=True, verbose_name='Core Present')),
                ('signal_present_server', models.BooleanField(null=True, verbose_name='Server Present')),
                ('signal_updated_access', models.BooleanField(null=True, verbose_name='Access Updated')),
                ('signal_updated_core', models.BooleanField(null=True, verbose_name='Core Updated')),
                ('signal_updated_server', models.BooleanField(null=True, verbose_name='Server Updated')),
                ('signal_updated_wan', models.BooleanField(null=True, verbose_name='WAN Updated')),
            ],
        ),
    ]
