from django import forms
from .models import Closet


class ClosetCreateForm(forms.ModelForm):
    class Meta:
        model = Closet
        fields = ['floor',
                  'category',
                  'closet',
                  ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['closet'].widget.attrs.update(readonly=True)
        self.fields['closet'].widget.attrs.update(placeholder='Autogenerated')


class ClosetCreateBaseModelFormset(forms.BaseModelFormSet):
    def __init__(self, *args, **kwargs):
        kwargs.pop('instance', None)
        super().__init__(*args, **kwargs)

    def _should_delete_form(self, form):
        form.full_clean()
        return super()._should_delete_form(form)


ClosetCreateFormset = forms.modelformset_factory(
    Closet, can_delete=True, extra=1, form=ClosetCreateForm, formset=ClosetCreateBaseModelFormset)
